languageCode = "en-in"
title = "Shakthi Palace"
enableGitInfo = true
enableRobotsTXT = true
theme = "github.com/ananthb/mandapam-theme"

[module]
[[module.imports]]
path = "github.com/ananthb/mandapam-theme"

[build.buildStats]
enable = true

[params]
github_repository = "shakthipalace/shakthipalace.com"
logo = "logos/shakthi-palace-logo-transparent.png"
[params.homepage_meta_tags]
meta_description = """
Shakthi Palace is a luxurious, air-conditioned wedding hall, reception hall, \
muhurtham venue, and event hall. Shakthi Palace is situated in Anbu Nagar, Valasaravakkam, Chennai. \
It has elevators, well-illuminated signage, fire-safety systems, roof-top dining, \
dining hall, and mini hall. 24x7 CCTV coverage is available to keep you and yours safe. \

Shakthi Sangita Sabha auditorium for kutcheris and classical arts performances is also available - visit shakthisangitasabha.com."""
meta_og_title = "Shakthi Palace"
meta_og_type = "website"
meta_og_url = "https://shakthipalace.com"
meta_og_image = "https://shakthipalace.com/shakthi-palace/shakthi-palace-logo-transparent.png"
meta_og_description = """
Shakthi Palace is a luxurious, air-conditioned wedding hall, reception hall, \
muhurtham venue, and event hall. Shakthi Palace is situated in Anbu Nagar, Valasaravakkam, Chennai. \
It has elevators, well-illuminated signage, fire-safety systems, roof-top dining, \
dining hall, and mini hall. 24x7 CCTV coverage is available to keep you and yours safe. \

Shakthi Sangita Sabha auditorium for kutcheris and classical arts performances is also available - visit shakthisangitasabha.com."""

[[menu.main]]
name = "Shakthi Palace"
url = "/"
weight = 1

[[menu.main]]
name = "Kalyana Mandapam"
url = "/kalyana-mandapam/"
weight = 2

[[menu.main]]
name = "Mini Hall"
url = "/mini-hall/"
weight = 3

[[menu.main]]
name = "Sangita Sabha"
url = "https://shakthisangitasabha.com"
weight = 4
[menu.main.params]
external = true

[[menu.main]]
name = "Facilities"
url = "/facilities/"
weight = 5

[[menu.main]]
name = "Moments"
url = "/gallery/"
weight = 6

[[menu.main]]
name = "Contact Us"
url = "/#contact"
weight = 7

[permalinks]
events = "/:year/:month/:day/:slug/"
venue = "/:contentbasename/"

[imaging.exif]
includeFields = ""
disableLatLong = true
